package pojo;
// Generated Oct 14, 2022 10:47:34 AM by Hibernate Tools 4.3.1

import DAO.DAOLogin;
import DAO.DAOuser;
import java.util.List;
import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;




/**
 * TblUser generated by hbm2java
 */
@ManagedBean
public class TblUser  implements java.io.Serializable {


     private Integer idUser;
     private String ussername;
     private String password;
     
     public String save_user()
     {
         DAOLogin add = new DAOLogin();
         add.add_user(this);
         return "sukses";
     }
     
     public String login_user()
     {
         DAOLogin uDao = new DAOLogin();
         List<TblUser> us = uDao.getBy(ussername, password);
         try {
             if (us !=null) 
         {
         ussername = us.get(0).ussername;
         password = us.get(0).password;
         //return "sukses";
         }
             
         } catch (Exception e) {
             System.out.println(e);
             //return "gagal";
         }
         
         return "sukses";
     }
     
     public List<TblUser> getAllRecords()
     {
         DAOuser usr = new DAOuser();
         List<TblUser> lUsr = usr.retrieveTblUser();
         return lUsr;
     }
     
     public String getById()
     {
         String id_user = idUser.toString();
         DAOuser usr = new DAOuser();
         List<TblUser> lUsr = usr.getbyID(id_user);
         ussername = lUsr.get(0).ussername;
         password = lUsr.get(0).password;
         return "sukses";
     }
     
     public void edit()
     {
         DAOuser usr = new DAOuser();
         usr.editUser(this);
         ussername = "";
         password = "";
         FacesMessage facesMessage = new FacesMessage(FacesMessage.SEVERITY_INFO,"berhasil update data", null);
     }
     
     public void delete()
     {
         String id_user = idUser.toString();
         DAOuser usr = new DAOuser();
         usr.deleteUser(idUser);
         ussername = "";
         password = "";
     }

    public TblUser() {
    }

    public TblUser(String ussername, String password) {
       this.ussername = ussername;
       this.password = password;
    }
   
    public Integer getIdUser() {
        return this.idUser;
    }
    
    public void setIdUser(Integer idUser) {
        this.idUser = idUser;
    }
    public String getUssername() {
        return this.ussername;
    }
    
    public void setUssername(String ussername) {
        this.ussername = ussername;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }




}